import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const source=await readFile('src/pages/美人桥商户钱包/美人桥商户钱包-demo.html','utf8');
const model=source.split('// MODEL_START')[1].split('// MODEL_END')[0];
const context=vm.createContext({Date,BigInt,Number,Error,JSON});
vm.runInContext(model+';globalThis.api={units,seedState,effectiveFee,feeFor,currentQuote,exchangePreview,createTopup,receiveTopup,manualConfirmTopup,cancelTopup,ensureCollectionDisplay,createExchange,ensureInstantExchange,saveMerchantFees,ensureMerchantDemo,merchantProfile,saveAccount,setGroup,archiveAccount,restoreAccount,changePasswordDemo,prepareImport,importAccounts,parseCSV,csvText};',context);
const a=context.api;
test('手续费二选一，商户覆盖全局且零手续费不误用全局',()=>{const s=a.seedState();assert.equal(a.feeFor(a.units('100'),a.effectiveFee(s,'beauty-a','exchange').rule),a.units('0.5'));assert.equal(a.feeFor(a.units('100'),a.effectiveFee(s,'beauty-b','exchange').rule),a.units('2'));s.merchants[1].fees.exchange={mode:'fixed',value:'0'};assert.equal(a.feeFor(a.units('100'),a.effectiveFee(s,'beauty-b','exchange').rule),0);s.merchants[1].fees=null;assert.equal(a.effectiveFee(s,'beauty-b','exchange').source,'全局设置')});
test('USDT/TRX上分原币自动入账，重复通知不重复增加且商户互不影响',()=>{const s=a.seedState(),m=s.merchants[0],other=JSON.stringify(s.merchants[1]);for(const coin of ['USDT','TRX']){const key=coin.toLowerCase(),before=m[key],amount=a.units('100'),o=a.createTopup(s,m.id,coin,amount);assert.equal(m[key],before);assert.equal(a.receiveTopup(s,o.id),true);assert.equal(m[key],before+o.net);assert.equal(a.receiveTopup(s,o.id),false);assert.equal(m[key],before+o.net);assert.equal(s.ledger.filter(l=>l.order===o.id).length,1)}assert.equal(JSON.stringify(s.merchants[1]),other)});
test('确认兑换立即扣本金及USDT手续费并增加TRX，报价变动不改历史',()=>{const s=a.seedState(),m=s.merchants[0],before=m.usdt,trx=m.trx,other=JSON.stringify(s.merchants[1]),p=a.exchangePreview(s,m.id,a.units('100')),o=a.createExchange(s,m.id,p.amount,p,'instant-1');assert.equal(o.status,'success');assert.equal(o.time,o.completed);assert.equal(m.usdt,before-a.units('100.5'));assert.equal(m.trx,trx+a.units('800'));assert.equal(m.frozen,0);const entries=s.ledger.filter(l=>l.order===o.id);assert.equal(entries.length,2);assert.equal(entries.find(l=>l.coin==='USDT').amount,-a.units('100.5'));assert.equal(entries.find(l=>l.coin==='TRX').amount,a.units('800'));assert.equal(JSON.stringify(s.merchants[1]),other);s.quote.manual='12';s.quote.mode='manual';s.quote.revision++;s.globalFees.exchange.value='9';assert.equal(o.trx,a.units('800'));assert.equal(o.total,a.units('100.5'))});
test('重复兑换请求只记账一次，即使后续行情中断，篡改重复请求会拒绝',()=>{const s=a.seedState(),m=s.merchants[0],p=a.exchangePreview(s,m.id,a.units('100')),o=a.createExchange(s,m.id,p.amount,p,'repeat-1'),after=JSON.stringify(s);s.quote.available=false;const beforeRepeat=JSON.stringify(s);assert.equal(a.createExchange(s,m.id,p.amount,p,'repeat-1'),o);assert.equal(JSON.stringify(s),beforeRepeat);assert.equal(s.ledger.filter(l=>l.order===o.id).length,2);assert.throws(()=>a.createExchange(s,'beauty-b',p.amount,p,'repeat-1'),/不一致/);assert.throws(()=>a.createExchange(s,m.id,a.units('200'),p,'repeat-1'),/不一致/);assert.equal(JSON.stringify(s),beforeRepeat);assert.ok(after)});
test('行情异常阻止新兑换，手动切价后恢复，已完成订单报价与金额不变',()=>{const s=a.seedState(),m=s.merchants[0],p=a.exchangePreview(s,m.id,a.units('100')),old=a.createExchange(s,m.id,p.amount,p,'market-1'),snapshot=JSON.stringify(old);s.quote.available=false;assert.throws(()=>a.exchangePreview(s,m.id,a.units('100')),/行情不可用/);s.quote.mode='manual';s.quote.manual='9';s.quote.revision++;const next=a.exchangePreview(s,m.id,a.units('100'));assert.equal(next.trx,a.units('900'));assert.equal(next.source,'手动汇率');a.createExchange(s,m.id,next.amount,next,'market-2');assert.equal(JSON.stringify(old),snapshot)});
test('预览到确认期间报价或手续费变化须重新确认，失败不改变账本',()=>{for(const key of ['quote','fee']){const s=a.seedState(),m=s.merchants[0],p=a.exchangePreview(s,m.id,a.units('100'));if(key==='quote'){s.quote.rates['交易所 A']='9';s.quote.revision++}else{s.globalFees.exchange.value='2'}const before=JSON.stringify(s);assert.throws(()=>a.createExchange(s,m.id,p.amount,p,'changed-'+key),/已更新/);assert.equal(JSON.stringify(s),before)}});
test('无效金额、余额不足、TRX溢出或缺少请求标识不产生部分扣款',()=>{for(const raw of ['1e-6','-1','1.1234567','NaN'])assert.throws(()=>a.units(raw));const s=a.seedState();assert.throws(()=>a.createTopup(s,'beauty-b','USDT',a.units('1')),/大于手续费/);let p=a.exchangePreview(s,'beauty-a',a.units('20000')),before=JSON.stringify(s);assert.throws(()=>a.createExchange(s,'beauty-a',p.amount,p,'insufficient'),/余额不足/);assert.equal(JSON.stringify(s),before);s.merchants[0].trx=Number.MAX_SAFE_INTEGER;p=a.exchangePreview(s,'beauty-a',a.units('100'));before=JSON.stringify(s);assert.throws(()=>a.createExchange(s,'beauty-a',p.amount,p,'overflow'),/超出/);assert.equal(JSON.stringify(s),before);assert.throws(()=>a.createExchange(s,'beauty-a',p.amount,p),/请求标识/);assert.equal(JSON.stringify(s),before)});
test('旧版未完成演示订单释放冻结、保留锁价，不补扣款且迁移仅一次',()=>{const s=a.seedState(),m=s.merchants[0],completed=JSON.stringify(s.exchanges[0]),beforeUSDT=m.usdt,beforeTRX=m.trx;for(const status of ['pending','processing'])s.exchanges.push({id:'OLD-'+status,merchant:m.id,amount:a.units('100'),fee:a.units('0.5'),total:a.units('100.5'),trx:a.units('800'),rate:a.units('8'),status,time:'2026-10-09 10:00:00'});m.frozen=a.units('201');const beforeLedger=JSON.stringify(s.ledger);a.ensureInstantExchange(s);assert.equal(m.frozen,0);assert.equal(m.usdt,beforeUSDT);assert.equal(m.trx,beforeTRX);assert.equal(JSON.stringify(s.ledger),beforeLedger);assert.equal(JSON.stringify(s.exchanges[0]),completed);assert.ok(s.exchanges.slice(1).every(o=>o.status==='cancelled'&&o.rate===a.units('8')));const after=JSON.stringify(s);a.ensureInstantExchange(s);assert.equal(JSON.stringify(s),after)});
test('单独手续费开关覆盖或回退全局，关闭保留草稿，零费用有效',()=>{const s=a.seedState(),fees={topupUSDT:{mode:'fixed',value:'0'},topupTRX:{mode:'fixed',value:'2'},exchange:{mode:'percent',value:'1'}};a.saveMerchantFees(s,'beauty-a',true,fees);assert.equal(a.feeFor(a.units('100'),a.effectiveFee(s,'beauty-a','topupUSDT').rule),0);assert.equal(a.feeFor(a.units('100'),a.effectiveFee(s,'beauty-a','exchange').rule),a.units('1'));a.saveMerchantFees(s,'beauty-a',false,null);assert.equal(s.merchants[0].fees,null);assert.equal(s.merchants[0].feeDraft,fees);assert.equal(a.effectiveFee(s,'beauty-a','exchange').source,'全局设置');assert.equal(a.feeFor(a.units('100'),a.effectiveFee(s,'beauty-a','exchange').rule),a.units('0.5'));a.saveMerchantFees(s,'beauty-a',true,s.merchants[0].feeDraft);assert.equal(a.effectiveFee(s,'beauty-a','exchange').source,'商户设置')});
test('钱包导航仅美人桥端和后台美人桥业务，其他端不混入',async()=>{const c=JSON.parse(await readFile('src/catalog/project.json','utf8'));const group=c.nav.ADMIN.find(g=>g.label==='美人桥业务');assert.deepEqual(group.items.filter(x=>x.req.includes('BP-REQ-017')&&!x.hidden).map(x=>x.title),['商户管理','钱包管理']);assert.equal(group.items.filter(x=>x.hidden&&x.parent==='admin-beauty-wallet-management').length,4);assert.equal(c.nav.BEAUTY_MERCHANT[0].items.filter(x=>x.req?.includes('BP-REQ-017')).length,2);assert.ok(!c.nav.MERCHANT.flatMap(g=>g.items||[]).some(x=>x.req?.includes('BP-REQ-017')));assert.ok(!c.nav.ADMIN.filter(g=>g!==group).flatMap(g=>g.items||[]).some(x=>x.req?.includes('BP-REQ-017')))});

const profile={number:'DEMO-NEW-TEST',name:'测试演示商户',owner:'演示归属',contact:'DEMO-CONTACT',deposit:'10',rate:'1',floating:'0.1',pool:'TRX',agent:'',tgGroup:'',bot:'',enabled:true};
test('商户资料可完整编辑但保持钱包、手续费与历史订单，编号唯一',()=>{const s=a.seedState(),m=s.merchants[0],before={usdt:m.usdt,trx:m.trx,frozen:m.frozen,fees:m.fees,orders:JSON.stringify(s.exchanges)};a.saveAccount(s,m.id,null,{...profile});assert.equal(m.name,profile.name);assert.equal(a.merchantProfile(m).number,profile.number);assert.deepEqual({usdt:m.usdt,trx:m.trx,frozen:m.frozen,fees:m.fees,orders:JSON.stringify(s.exchanges)},before);assert.throws(()=>a.saveAccount(s,null,null,profile,'demo','demo'),/已存在/);assert.throws(()=>a.saveAccount(s,null,null,{...profile,number:'OTHER',owner:''},'demo','demo'),/归属/)});
test('新增商户初始化零钱包，子账户不创建独立钱包且父商户资金不受影响',()=>{const s=a.seedState(),before=JSON.stringify(s.merchants[0]);assert.throws(()=>a.saveAccount(s,null,null,profile,'demo','wrong'),/不一致/);const added=a.saveAccount(s,null,null,profile,'demo','demo');assert.equal(added.usdt,0);assert.equal(added.trx,0);assert.equal(added.fees,null);const parent=s.merchants[0],wallet={usdt:parent.usdt,trx:parent.trx,frozen:parent.frozen},count=s.merchants.length;const child=a.saveAccount(s,null,parent.id,{...profile,number:'CHILD-TEST'},'demo','demo');assert.equal(s.merchants.length,count);assert.equal(parent.subaccounts[0],child);assert.ok(!('usdt' in child));assert.ok(!('trx' in child));assert.ok(!('fees' in child));assert.deepEqual({usdt:parent.usdt,trx:parent.trx,frozen:parent.frozen},wallet);assert.ok(before)});
test('绑定和解绑仅作用于所选商户，无效批次不部分更新',()=>{const s=a.ensureMerchantDemo(a.seedState());a.setGroup(s,['beauty-a','beauty-b'],'测试分组1');assert.equal(a.merchantProfile(s.merchants[0]).group,'测试分组1');assert.equal(a.merchantProfile(s.merchants[1]).group,'测试分组1');assert.equal(a.merchantProfile(s.merchants[2]).group,'演示分组');assert.throws(()=>a.setGroup(s,['beauty-a'],'12345678901'),/最多10/);assert.throws(()=>a.setGroup(s,['beauty-a','MISSING'],'其他分组'));assert.equal(a.merchantProfile(s.merchants[0]).group,'测试分组1');a.setGroup(s,['beauty-a'],'');assert.equal(a.merchantProfile(s.merchants[0]).group,'');assert.equal(a.merchantProfile(s.merchants[1]).group,'测试分组1')});
test('可恢复删除保留原币余额、冻结、子账户和资金记录，密码演示不保存凭证',()=>{const s=a.seedState(),m=s.merchants[0],p=a.exchangePreview(s,m.id,a.units('100'));a.createExchange(s,m.id,p.amount,p,'archive-1');const funds=JSON.stringify({usdt:m.usdt,trx:m.trx,frozen:m.frozen,ledger:s.ledger,orders:s.exchanges});a.archiveAccount(s,m.id);assert.equal(m.deleted,true);assert.equal(JSON.stringify({usdt:m.usdt,trx:m.trx,frozen:m.frozen,ledger:s.ledger,orders:s.exchanges}),funds);a.restoreAccount(s,m.id);assert.equal(m.deleted,false);assert.throws(()=>a.changePasswordDemo(s,m.id,null,'demo','wrong','123456'),/不一致/);assert.throws(()=>a.changePasswordDemo(s,m.id,null,'demo','demo','1'),/6位/);a.changePasswordDemo(s,m.id,null,'DEMO-SECRET','DEMO-SECRET','123456');assert.ok(!JSON.stringify(s).includes('DEMO-SECRET'));assert.ok(!JSON.stringify(s).includes('123456'))});
const header='美人桥号,代理id,商户名称,归属,联系方式,押金,费率,上浮费率,地址池标识,TG群ID,通知机器人,是否启用';
test('批量导入先全量校验，重复号或无效金额不部分新增，合法导入零钱包',()=>{const s=a.seedState(),before=JSON.stringify(s),good='IMPORT-01,,演示导入,演示归属,DEMO,0,1,0,TRX,,,启用';assert.throws(()=>a.importAccounts(s,header+'\n'+good+'\n'+good),/重复/);assert.equal(JSON.stringify(s),before);assert.throws(()=>a.importAccounts(s,header+'\n'+good+'\nIMPORT-02,,演示导入,演示归属,DEMO,-1,1,0,TRX,,,启用'));assert.equal(JSON.stringify(s),before);assert.equal(a.importAccounts(s,header+'\n'+good),1);const m=s.merchants.at(-1);assert.equal(m.usdt,0);assert.equal(m.trx,0);assert.equal(m.frozen,0);assert.equal(m.needsInitialPassword,true);assert.throws(()=>a.prepareImport(s,header+'\n'+good),/重复/)});
test('CSV支持BOM、引号、逗号及换行，导出阻止表格公式执行',()=>{const parsed=a.parseCSV('\uFEFFa,b\r\n"含,逗号","含\n换行"\r\n"双""引号",值');assert.equal(parsed[1][0],'含,逗号');assert.equal(parsed[1][1],'含\n换行');assert.equal(parsed[2][0],'双"引号');assert.throws(()=>a.parseCSV('a,b\n"未闭合'),/未闭合/);const out=a.csvText([['=SUM(1,2)','正常','-100']]);assert.ok(out.includes("'=SUM"));assert.ok(out.includes("'-100"))});
test('演示数据迁移不覆盖原商户钱包，重复迁移不重复补充',()=>{const s=a.seedState();s.merchants[0].usdt=a.units('123');a.ensureMerchantDemo(s);assert.equal(s.merchants.length,23);assert.equal(s.merchants[0].usdt,a.units('123'));a.ensureMerchantDemo(s);assert.equal(s.merchants.length,23)});

test('上分地址按订单持久保存，重新查看和到账后仍用同一地址，兼容旧单不覆盖已有分配',()=>{const s=a.seedState();a.ensureCollectionDisplay(s);const usdt=a.createTopup(s,'beauty-a','USDT',a.units('500')),trx=a.createTopup(s,'beauty-a','TRX',a.units('100')),u=JSON.stringify(usdt.collection),t=JSON.stringify(trx.collection);assert.equal(usdt.collection.address,'TDEMO9zP4kX7vM2qR5sL8nC1wF6aB3h');assert.equal(trx.collection.address,'TDEMOTrx9zP4kX7vM2qR5sL8nC1wF6a');const reloaded=JSON.parse(JSON.stringify(s));a.ensureCollectionDisplay(reloaded);assert.equal(JSON.stringify(reloaded.topups.find(o=>o.id===usdt.id).collection),u);a.receiveTopup(reloaded,usdt.id);assert.equal(JSON.stringify(reloaded.topups.find(o=>o.id===usdt.id).collection),u);assert.equal(JSON.stringify(reloaded.topups.find(o=>o.id===trx.id).collection),t);reloaded.topups[0].collection={address:'EXISTING-ASSIGNMENT',network:'已有网络',demo:true};a.ensureCollectionDisplay(reloaded);assert.equal(reloaded.topups[0].collection.address,'EXISTING-ASSIGNMENT');assert.equal(reloaded.topups[0].collection.network,'已有网络')});


test('手动确认按本单费用原币净入账，与自动到账竞争仅记账一次且留操作说明',()=>{for(const coin of ['USDT','TRX']){const s=a.seedState(),m=s.merchants[0],key=coin.toLowerCase(),before=m[key],o=a.createTopup(s,m.id,coin,a.units('100'));const snapshot=JSON.stringify(s);assert.throws(()=>a.manualConfirmTopup(s,o.id,'  '),/核验说明/);assert.equal(JSON.stringify(s),snapshot);s.globalFees['topup'+coin].value='50';assert.equal(a.manualConfirmTopup(s,o.id,'链上核验已收款，自动检查异常'),true);assert.equal(m[key],before+o.net);assert.equal(o.resolution.mode,'manual');assert.ok(o.resolution.reason.includes('核验'));assert.equal(s.ledger.filter(l=>l.order===o.id).length,1);const after=JSON.stringify(s);assert.equal(a.receiveTopup(s,o.id),false);assert.throws(()=>a.manualConfirmTopup(s,o.id,'重复人工请求'),/已结束/);assert.throws(()=>a.cancelTopup(s,o.id,'取消成功单'),/已结束/);assert.equal(JSON.stringify(s),after)}});
test('取消待收款订单不改变资金，迟到回执和人工确认不能再次入账',()=>{const s=a.seedState(),o=a.createTopup(s,'beauty-a','TRX',a.units('100')),funds=JSON.stringify({merchants:s.merchants,ledger:s.ledger});assert.throws(()=>a.cancelTopup(s,o.id,''),/取消原因/);assert.equal(o.status,'waiting');a.cancelTopup(s,o.id,'商户取消本次充值');assert.equal(o.status,'cancelled');assert.equal(o.resolution.reason,'商户取消本次充值');assert.equal(JSON.stringify({merchants:s.merchants,ledger:s.ledger}),funds);const after=JSON.stringify(s);assert.equal(a.receiveTopup(s,o.id),false);assert.throws(()=>a.manualConfirmTopup(s,o.id,'迟到资金'),/已结束/);assert.throws(()=>a.cancelTopup(s,o.id,'重复取消'),/已结束/);assert.equal(JSON.stringify(s),after)});
test('自动到账先完成时拒绝后到的运营操作，余额溢出时人工确认不部分写入',()=>{const s=a.seedState(),o=a.createTopup(s,'beauty-a','USDT',a.units('100'));a.receiveTopup(s,o.id);const after=JSON.stringify(s);assert.equal(o.resolution.mode,'automatic');assert.throws(()=>a.manualConfirmTopup(s,o.id,'后到人工确认'),/已结束/);assert.throws(()=>a.cancelTopup(s,o.id,'后到取消'),/已结束/);assert.equal(JSON.stringify(s),after);const overflow=a.createTopup(s,'beauty-a','USDT',a.units('100'));s.merchants[0].usdt=Number.MAX_SAFE_INTEGER;const before=JSON.stringify(s);assert.throws(()=>a.manualConfirmTopup(s,overflow.id,'已核实'),/超出/);assert.equal(JSON.stringify(s),before)});


test('钱包首页将编辑或导入的商户名按文本显示，不解析HTML',async()=>{const source=await readFile('src/pages/美人桥商户钱包/美人桥商户钱包-demo.html','utf8'),presentation=source.split('\n').filter(line=>['function esc(','function fmt(','function home(','function ledgerTable('].some(prefix=>line.startsWith(prefix))).join('\n'),renderContext=vm.createContext({Date,BigInt,Number,Error,JSON});vm.runInContext(model+'\n'+presentation+"\nconst currentMerchant='beauty-a';globalThis.renderHome=home;globalThis.newState=seedState;",renderContext);const s=renderContext.newState();s.merchants[0].name='<img src=x onerror="alert(1)"> & 商户';const page=renderContext.renderHome(s);assert.ok(!page.includes('<img'));assert.equal(page.split('&lt;img src=x onerror=&quot;alert(1)&quot;&gt; &amp; 商户').length-1,2)});
